### ISSUE TITLE
Error after creating Pinecone Index

### ISSUE THREAD

**Issue by giuliastro** [muellerberndt/micro-gpt#36]
Hello,
on first launch it correctly creates the index. But right after that micro-gpt stops with this error. It doesn't seem to be related to Pinecone since it does this right after it created the index, every time. Any ideas? Thank you in advance.

```
Creating Pinecode index...
Traceback (most recent call last):
  File "D:\Software\micro-gpt\microgpt.py", line 79, in <module>
    memory = get_memory_instance()
  File "D:\Software\micro-gpt\memory.py", line 335, in get_memory_instance
    return PineconeMemory()
  File "D:\Software\micro-gpt\memory.py", line 121, in __init__
    self.index.delete(deleteAll='true')
  File "C:\Users\Giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\utils\error_handling.py", line 17, in inner_func
    return func(*args, **kwargs)
  File "C:\Users\Giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\index.py", line 329, in delete
    return self._vector_api.delete(
  File "C:\Users\Giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "C:\Users\Giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api\vector_operations_api.py", line 117, in __delete
    return self.call_with_http_info(**kwargs)
  File "C:\Users\Giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "C:\Users\Giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
  File "C:\Users\Giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 207, in __call_api
    raise e
  File "C:\Users\Giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 200, in __call_api
    response_data = self.request(
  File "C:\Users\Giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\api_client.py", line 459, in request
    return self.rest_client.POST(url,
  File "C:\Users\Giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\rest.py", line 271, in POST
    return self.request("POST", url,
  File "C:\Users\Giulio\AppData\Local\Programs\Python\Python310\lib\site-packages\pinecone\core\client\rest.py", line 228, in request
    raise ServiceException(http_resp=r)
pinecone.core.client.exceptions.ServiceException: (503)
Reason: Service Unavailable
HTTP response headers: HTTPHeaderDict({'content-length': '0', 'date': 'Thu, 20 Apr 2023 17:32:04 GMT', 'server': 'envoy'})
```

**Comment by ismaelc** [comment]
> Reason: Service Unavailable

Pinecone down?

**Comment by muellerberndt** [comment]
> Pinecone down?

Sounds like. @giuliastro is it working for you now?

**Comment by giuliastro** [comment]
yes, there was a period of malfunctioning of Pinecone. I reported the problem here because through the Pinecone interface it was usable and I could manage the index, but every time I launched micro-gpt it went into error. It happened for a while and I reported it. Now it seems to go, thank you very much.
